interface colorTypes {
  primary: string,
  yellow: string,
  secondary: string,
  gray: string,
  gray1: string,
  gray2: string,
  white: string,
  red: string,
  red1: string,
  navy_blue: string,
  light_black: string,
  light_black1: string,
  light_black2: string,
  placeholder_color: string,
  heading: string,
  black: string,
  blue: string,
  green: string,
  green1: string,
  darkBlue: string
}

const themes: colorTypes = {
  primary: '#D9CA40',
  yellow: '#FFC22C',
  secondary: '#606060',
  gray: '#808080',
  gray1: '#D9D9D9',
  gray2: '#838FA0',
  white: '#FFFF',
  red: '#FB1C0F',
  red1: '#FF0000',
  navy_blue: '#181C2E',
  light_black: '#1C1B1B',
  light_black1: '#222222',
  light_black2: '#141414',
  placeholder_color: '#FFFEFE',
  heading: '#F9E4E5',
  black: 'black',
  blue: 'blue',
  green: 'green',
  green1: '#00FF0A',
  darkBlue: '#082A6B',
};

export default themes
